[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "meetup-host-ops-qr"
version = "0.0.1"
dependencies = ["qrcode[pil]", "more-itertools"]

[tool.setuptools]
py-modules = ["myqr"]
